### ISSUE TITLE
SWC links broken

### ISSUE THREAD

**Issue by dtwitty** [ethanwhite/progbio#3]
I believe the SWC readings have been migrated. The content still exists but the links are broken.

For example, the link to [Analyzing Patient Data](http://software-carpentry.org/v5/novice/python/01-numpy.html) is broken, but the content [still exists](http://swcarpentry.github.io/python-novice-inflammation/01-numpy/).

**Comment by ethanwhite** [comment]
Thanks for the report @dtwitty. We'd had to fix these several times in the past and we'll do it again as soon as we get the chance.

@brymz - would you mind sticking a link check and cleanup for the external material on this site on your To Do list for the next time you have a few spare hours?

**Comment by ethanwhite** [comment]
Closed in #4. Thanks again for reporting this @dtwitty and sorry for the delay. Thanks for fixing this @brymz!
